# Khám phá Dữ liệu Thô (MIMIC-IV)
Notebook này kết nối trực tiếp vào cơ sở dữ liệu PostgreSQL để hiển thị 30 dòng dữ liệu mẫu của 6 bảng thô.

In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

# Thông tin kết nối PostgreSQL
DB_USER = 'postgres'
DB_PASS = '12122004'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'mimic_iv'

# Tạo engine kết nối
engine = create_engine(f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

def view_table(schema, table_name, limit=30):
    query = f'SELECT * FROM {schema}.{table_name} LIMIT {limit}'
    df = pd.read_sql(query, engine)
    print(f'\n--- BẢNG {schema}.{table_name} (Hiển thị {limit} dòng) ---')
    display(df)

In [2]:
# 1. Nhóm Đặc trưng Chung (Nhân khẩu học & Hành trình)
view_table('hosp', 'patients')
view_table('hosp', 'admissions')

--- BẢNG hosp.patients (Hiển thị 30 dòng) ---

    subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0     10000032      F          52         2180       2014 - 2016  2180-09-09
1     10000048      F          23         2126       2008 - 2010        None
2     10000058      F          33         2168       2020 - 2022        None
3     10000068      F          19         2160       2008 - 2010        None
4     10000084      M          72         2160       2017 - 2019  2161-02-13
5     10000102      F          27         2136       2008 - 2010        None
6     10000108      M          25         2163       2014 - 2016        None
7     10000115      M          24         2154       2017 - 2019        None
8     10000117      F          48         2174       2008 - 2010        None
9     10000161      M          60         2163       2020 - 2022        None
10    10000178      F          59         2157       2017 - 2019        None
11    10000248      M          34         2192       2014 - 2016        None
12    10000280      M          20         2151       2008 - 2010        None
13    10000285      M          34         2159       2017 - 2019        None
14    10000459      M          63         2178       2011 - 2013        None
15    10000473      M          81         2138       2017 - 2019        None
16    10000492      M          22         2129       2017 - 2019        None
17    10000507      M          19         2151       2017 - 2019        None
18    10000526      F          30         2160       2014 - 2016        None
19    10000560      F          53         2189       2008 - 2010        None
20    10000594      M          32         2132       2011 - 2013        None
21    10000635      F          74         2136       2014 - 2016        None
22    10000650      M          30         2142       2008 - 2010        None
23    10000683      F          29         2175       2008 - 2010        None
24    10000690      F          86         2150       2008 - 2010  2152-01-30
25    10000719      F          34         2140       2008 - 2010        None
26    10000764      M          86         2132       2014 - 2016        None
27    10000826      F          32         2146       2008 - 2010        None
28    10000883      M          20         2124       2008 - 2010        None
29    10000886      M          18         2178       2008 - 2010        None

--- BẢNG hosp.admissions (Hiển thị 30 dòng) ---

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,None,URGENT,P49AFC,TRANSFER FROM HOSPITAL,HOME,Medicaid,English,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,None,EW EMER.,P784FA,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,None,EW EMER.,P19UTS,EMERGENCY ROOM,HOSPICE,Medicaid,English,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
3,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,None,EW EMER.,P06OTX,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,None,EU OBSERVATION,P39NWO,EMERGENCY ROOM,None,None,English,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0
5,10000084,23052089,2160-11-21 01:56:00,2160-11-25 14:52:00,None,EW EMER.,P42H7G,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Medicare,English,MARRIED,WHITE,2160-11-20 20:36:00,2160-11-21 03:20:00,0
6,10000084,29888819,2160-12-28 05:11:00,2160-12-28 16:07:00,None,EU OBSERVATION,P35NE4,PHYSICIAN REFERRAL,None,Medicare,English,MARRIED,WHITE,2160-12-27 18:32:00,2160-12-28 16:07:00,0
7,10000108,27250926,2163-09-27 23:17:00,2163-09-28 09:04:00,None,EU OBSERVATION,P40JML,EMERGENCY ROOM,None,None,English,SINGLE,WHITE,2163-09-27 16:18:00,2163-09-28 09:04:00,0
8,10000117,22927623,2181-11-15 02:05:00,2181-11-15 14:52:00,None,EU OBSERVATION,P47EY8,EMERGENCY ROOM,None,Medicaid,English,DIVORCED,WHITE,2181-11-14 21:51:00,2181-11-15 09:57:00,0
9,10000117,27988844,2183-09-18 18:10:00,2183-09-21 16:30:00,None,OBSERVATION ADMIT,P13ACE,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Medicaid,English,DIVORCED,WHITE,2183-09-18 08:41:00,2183-09-18 20:20:00,0
10,10000161,22148160,2163-08-20 01:42:00,2163-08-20 16:33:00,None,EU OBSERVATION,P73O7K,PHYSICIAN REFERRAL,None,Medicaid,English,SINGLE,WHITE,2163-08-19 22:35:00,2163-08-20 16:33:00,0
11,10000248,20600184,2192-11-30 01:25:00,2192-11-30 19:20:00,None,EU OBSERVATION,P416B5,EMERGENCY ROOM,None,Private,English,MARRIED,WHITE,2192-11-29 18:44:00,2192-11-30 03:32:00,0
12,10000280,25852320,2151-03-18 03:28:00,2151-03-18 17:04:00,None,EU OBSERVATION,P60DDG,EMERGENCY ROOM,None,Private,English,None,OTHER,2151-03-18 02:35:00,2151-03-18 17:04:00,0
13,10000560,28979390,2189-10-15 10:30:00,2189-10-17 15:00:00,None,SURGICAL SAME DAY ADMISSION,P64FPX,PHYSICIAN REFERRAL,HOME,Private,English,MARRIED,WHITE,NaT,NaT,0
14,10000635,20642640,2143-12-23 14:55:00,2143-12-24 12:52:00,None,EU OBSERVATION,P553YZ,WALK-IN/SELF REFERRAL,None,Medicare,English,WIDOWED,BLACK/AFRICAN AMERICAN,2143-12-23 07:43:00,2143-12-24 12:52:00,0
15,10000635,26134563,2136-06-19 14:24:00,2136-06-20 11:30:00,None,AMBULATORY OBSERVATION,P96UW1,PROCEDURE SITE,None,Medicare,English,WIDOWED,BLACK/AFRICAN AMERICAN,NaT,NaT,0
16,10000690,23280645,2150-09-16 19:48:00,2150-09-24 13:50:00,None,EW EMER.,P941QM,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,English,WIDOWED,WHITE,2150-09-16 16:00:00,2150-09-16 21:03:00,0
17,10000690,25860671,2150-11-02 18:02:00,2150-11-12 13:45:00,None,EW EMER.,P26QQ4,EMERGENCY ROOM,REHAB,Medicare,English,WIDOWED,WHITE,2150-11-02 11:41:00,2150-11-02 19:37:00,0
18,10000690,26146595,2152-01-28 23:40:00,2152-01-30 15:56:00,None,EW EMER.,P61PLH,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,English,WIDOWED,WHITE,2152-01-28 15:41:00,2152-01-29 01:22:00,0
19,10000690,26504700,2150-07-03 02:46:00,2150-07-07 15:42:00,None,EW EMER.,P46JQK,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,English,WIDOWED,WHITE,2150-07-02 22:59:00,2150-07-03 03:55:00,0
20,10000719,24558333,2140-04-15 00:14:00,2140-04-18 12:29:00,None,URGENT,P79PTN,PHYSICIAN REFERRAL,HOME,Private,English,SINGLE,WHITE,NaT,NaT,0
21,10000764,27897940,2132-10-14 23:31:00,2132-10-19 16:30:00,None,URGENT,P38YR6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Medicare,English,SINGLE,WHITE,2132-10-14 19:31:00,2132-10-15 16:45:00,0
22,10000826,20032235,2146-12-05 19:07:00,2146-12-12 16:30:00,None,EW EMER.,P278S6,EMERGENCY ROOM,HOME,Private,English,SINGLE,WHITE,2146-12-05 11:09:00,2146-12-05 20:54:00,0
23,10000826,21086876,2146-12-18 17:39:00,2146-12-24 19:55:00,None,DIRECT EMER.,P61YAW,CLINIC REFERRAL,HOME,Private,English,SINGLE,WHITE,NaT,NaT,0
24,10000826,28289260,2146-12-31 00:43:00,2147-01-02 17:45:00,None,EW EMER.,P19UTS,EMERGENCY ROOM,HOME,Private,English,SINGLE,WHITE,2146-12-30 17:06:00,2146-12-31 02:10:00,0
25,10000883,25221576,2124-05-14 21:11:00,2124-05-22 10:40:00,None,DIRECT EMER.,P23VE8,PHYSICIAN REFERRAL,HOME,Private,English,SINGLE,WHITE,2124-05-14 15:13:00,2124-05-14 21:35:00,0
26,10000883,29957930,2124-05-14 17:25:00,2124-05-14 21:10:00,None,EU OBSERVATION,P47DQU,EMERGENCY ROOM,None,Private,English,SINGLE,WHITE,2124-05-14 15:13:00,2124-05-14 21:35:00,0
27,10000886,21927847,2178-05-08 08:07:00,2178-05-08 11:46:00,None,EU OBSERVATION,P24H0T,EMERGENCY ROOM,None,None,English,SINGLE,UNABLE TO OBTAIN,2178-05-08 03:40:00,2178-05-08 11:46:00,0
28,10000904,28328117,2180-10-09 15:55:00,2180-10-10 15:59:00,None,DIRECT OBSERVATION,P51NG9,CLINIC REFERRAL,None,Private,English,SINGLE,WHITE,NaT,NaT,0
29,10000935,21738619,2187-07-11 13:06:00,2187-07-12 11:15:00,None,EU OBSERVATION,P086OF,EMERGENCY ROOM,None,Medicare,English,SINGLE,BLACK/AFRICAN AMERICAN,2187-07-11 09:26:00,2187-07-11 20:09:00,0

In [3]:
# 2. Nhóm Bệnh nền & Từ điển ICD (Phục vụ Private B)
view_table('hosp', 'diagnoses_icd')
view_table('hosp', 'd_icd_diagnoses')

--- BẢNG hosp.diagnoses_icd (Hiển thị 30 dòng) ---

    subject_id   hadm_id  seq_num icd_code  icd_version
0     10000032  22595853        1     5723            9
1     10000032  22595853        2    78959            9
2     10000032  22595853        3     5715            9
3     10000032  22595853        4    07070            9
4     10000032  22595853        5      496            9
5     10000032  22595853        6    29680            9
6     10000032  22595853        7    30981            9
7     10000032  22595853        8    V1582            9
8     10000032  22841357        1    07071            9
9     10000032  22841357        2    78959            9
10    10000032  22841357        3     2875            9
11    10000032  22841357        4     2761            9
12    10000032  22841357        5      496            9
13    10000032  22841357        6     5715            9
14    10000032  22841357        7      V08            9
15    10000032  22841357        8     3051            9
16    10000032  25742920        1    07054            9
17    10000032  25742920        2    78959            9
18    10000032  25742920        3     V462            9
19    10000032  25742920        4     5715            9
20    10000032  25742920        5     2767            9
21    10000032  25742920        6     2761            9
22    10000032  25742920        7      496            9
23    10000032  25742920        8      V08            9
24    10000032  25742920        9     3051            9
25    10000032  25742920       10    78791            9
26    10000032  29079034        1    45829            9
27    10000032  29079034        2    07044            9
28    10000032  29079034        3     7994            9
29    10000032  29079034        4     2761            9

--- BẢNG hosp.d_icd_diagnoses (Hiển thị 30 dòng) ---

   icd_code  icd_version                                         long_title
0      0010            9                     Cholera due to vibrio cholerae
1      0011            9              Cholera due to vibrio cholerae el tor
2      0019            9                               Cholera, unspecified
3      0020            9                                      Typhoid fever
4      0021            9                                Paratyphoid fever A
5      0022            9                                Paratyphoid fever B
6      0023            9                                Paratyphoid fever C
7      0029            9                     Paratyphoid fever, unspecified
8      0030            9                         Salmonella gastroenteritis
9      0031            9                              Salmonella septicemia
10    00320            9        Localized salmonella infection, unspecified
11    00321            9                              Salmonella meningitis
12    00322            9                               Salmonella pneumonia
13    00323            9                               Salmonella arthritis
14    00324            9                           Salmonella osteomyelitis
15    00329            9              Other localized salmonella infections
16     0038            9              Other specified salmonella infections
17     0039            9                  Salmonella infection, unspecified
18     0040            9                               Shigella dysenteriae
19     0041            9                                  Shigella flexneri
20     0042            9                                    Shigella boydii
21     0043            9                                    Shigella sonnei
22     0048            9                Other specified shigella infections
23     0049            9                           Shigellosis, unspecified
24     0050            9                      Staphylococcal food poisoning
25     0051            9                            Botulism food poisoning
26     0052            9  Food poisoning due to Clostridium perfringens ...
27     0053            9             Food poisoning due to other Clostridia
28     0054            9      Food poisoning due to Vibrio parahaemolyticus
29    00581            9            Food poisoning due to Vibrio vulnificus

In [4]:
# 3. Nhóm Sinh hiệu tại giường - Vitals (Phục vụ Private A & Shared)
view_table('icu', 'chartevents')

--- BẢNG icu.chartevents (Hiển thị 30 dòng) ---

,subject_id,hadm_id,stay_id,caregiver_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
0,10000032,29079034,39553978,18704,2180-07-23 12:36:00,2180-07-23 14:45:00,226512,39.4,39.4,kg,0
1,10000032,29079034,39553978,18704,2180-07-23 12:36:00,2180-07-23 14:45:00,226707,60,60.0,Inch,0
2,10000032,29079034,39553978,18704,2180-07-23 12:36:00,2180-07-23 14:45:00,226730,152,152.0,cm,0
3,10000032,29079034,39553978,18704,2180-07-23 14:00:00,2180-07-23 14:18:00,220048,SR (Sinus Rhythm),NaN,None,0
4,10000032,29079034,39553978,18704,2180-07-23 14:00:00,2180-07-23 14:18:00,224642,Oral,NaN,None,0
5,10000032,29079034,39553978,18704,2180-07-23 14:00:00,2180-07-23 14:18:00,224650,None,NaN,None,0
6,10000032,29079034,39553978,18704,2180-07-23 14:00:00,2180-07-23 14:20:00,223761,98.7,98.7,Â°F,0
7,10000032,29079034,39553978,18704,2180-07-23 14:11:00,2180-07-23 14:17:00,220179,84,84.0,mmHg,0
8,10000032,29079034,39553978,18704,2180-07-23 14:11:00,2180-07-23 14:17:00,220180,48,48.0,mmHg,0
9,10000032,29079034,39553978,18704,2180-07-23 14:11:00,2180-07-23 14:17:00,220181,56,56.0,mmHg,0
10,10000032,29079034,39553978,18704,2180-07-23 14:12:00,2180-07-23 14:17:00,220045,91,91.0,bpm,0
11,10000032,29079034,39553978,18704,2180-07-23 14:12:00,2180-07-23 14:17:00,220210,24,24.0,insp/min,0
12,10000032,29079034,39553978,18704,2180-07-23 14:13:00,2180-07-23 14:17:00,220277,98,98.0,%,0
13,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223781,Yes,NaN,None,0
14,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223782,Aching,NaN,None,0
15,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223783,Abdominal,NaN,None,0
16,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223784,At Rest,NaN,None,0
17,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223784,Injury,NaN,None,0
18,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223791,Moderate to Severe.,7.0,None,0
19,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223794,Yes,NaN,None,0
20,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223795,Patient Verbalized,NaN,None,0
21,10000032,29079034,39553978,18704,2180-07-23 14:15:00,2180-07-23 14:16:00,223796,None,NaN,None,0
22,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,220046,120,120.0,bpm,0
23,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,220047,60,60.0,bpm,0
24,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,223751,160,160.0,mmHg,0
25,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,223752,80,80.0,mmHg,0
26,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,223769,100,100.0,%,0
27,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,223770,92,92.0,%,0
28,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,224161,35,35.0,insp/min,0
29,10000032,29079034,39553978,18704,2180-07-23 14:17:00,2180-07-23 14:17:00,224162,8,8.0,insp/min,0

In [5]:
# 4. Nhóm Xét nghiệm Hóa sinh - Labs (Phục vụ Private A)
view_table('hosp', 'labevents')

--- BẢNG hosp.labevents (Hiển thị 30 dòng) ---

,labevent_id,subject_id,hadm_id,specimen_id,itemid,order_provider_id,charttime,storetime,value,valuenum,valueuom,ref_range_lower,ref_range_upper,flag,priority,comments
0,1,10000032,None,2704548,50931,P69FQC,2180-03-23 11:51:00,2180-03-23 15:56:00,___,95.0,mg/dL,70.0,100.0,None,ROUTINE,"IF FASTING, 70-100 NORMAL, >125 PROVISIONAL DI..."
1,2,10000032,None,36092842,51071,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,None
2,3,10000032,None,36092842,51074,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,None
3,4,10000032,None,36092842,51075,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,BENZODIAZEPINE IMMUNOASSAY SCREEN DOES NOT DET...
4,5,10000032,None,36092842,51079,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,None
5,6,10000032,None,36092842,51087,P69FQC,2180-03-23 11:51:00,NaT,None,NaN,None,NaN,NaN,None,ROUTINE,RANDOM.
6,7,10000032,None,36092842,51089,P69FQC,2180-03-23 11:51:00,2180-03-23 16:15:00,None,NaN,None,NaN,NaN,None,ROUTINE,PRESUMPTIVELY POSITIVE.
7,8,10000032,None,36092842,51090,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,METHADONE ASSAY DETECTS ONLY METHADONE (NOT OT...
8,9,10000032,None,36092842,51092,P69FQC,2180-03-23 11:51:00,2180-03-23 16:00:00,NEG,NaN,None,NaN,NaN,None,ROUTINE,OPIATE IMMUNOASSAY SCREEN DOES NOT DETECT SYNT...
9,10,10000032,None,83925500,50853,P69FQC,2180-03-23 11:51:00,2180-03-25 11:06:00,___,15.0,ng/mL,30.0,60.0,abnormal,ROUTINE,NEW ASSAY IN USE ___: DETECTS D2 AND D3 25-OH ...
10,11,10000032,None,83925500,50861,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,102,102.0,IU/L,0.0,40.0,abnormal,ROUTINE,None
11,12,10000032,None,83925500,50862,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,3.3,3.3,g/dL,3.5,5.2,abnormal,ROUTINE,None
12,13,10000032,None,83925500,50863,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,109,109.0,IU/L,35.0,105.0,abnormal,ROUTINE,None
13,14,10000032,None,83925500,50864,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,___,8.0,ng/mL,0.0,8.7,None,ROUTINE,MEASURED BY ___.
14,15,10000032,None,83925500,50868,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,12,12.0,mEq/L,8.0,20.0,None,ROUTINE,None
15,16,10000032,None,83925500,50878,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,143,143.0,IU/L,0.0,40.0,abnormal,ROUTINE,None
16,17,10000032,None,83925500,50882,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,27,27.0,mEq/L,22.0,32.0,None,ROUTINE,None
17,18,10000032,None,83925500,50885,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,1.6,1.6,mg/dL,0.0,1.5,abnormal,ROUTINE,None
18,19,10000032,None,83925500,50893,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,8.4,8.4,mg/dL,8.4,10.3,None,ROUTINE,None
19,20,10000032,None,83925500,50900,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,___,6.1,ng/mL,0.0,4.0,abnormal,ROUTINE,MEASURED BY ___.
20,21,10000032,None,83925500,50902,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,101,101.0,mEq/L,96.0,108.0,None,ROUTINE,None
21,22,10000032,None,83925500,50903,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,3.9,3.9,Ratio,NaN,NaN,None,ROUTINE,None
22,23,10000032,None,83925500,50904,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,52,52.0,mg/dL,NaN,NaN,None,ROUTINE,None
23,24,10000032,None,83925500,50905,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,135,135.0,mg/dL,0.0,129.0,abnormal,ROUTINE,None
24,25,10000032,None,83925500,50907,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,202,202.0,mg/dL,0.0,199.0,abnormal,ROUTINE,None
25,26,10000032,None,83925500,50912,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,0.4,0.4,mg/dL,0.4,1.1,None,ROUTINE,None
26,27,10000032,None,83925500,50920,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,None,NaN,None,NaN,NaN,None,ROUTINE,"Using this patient's age, gender, and serum cr..."
27,28,10000032,None,83925500,50922,P69FQC,2180-03-23 11:51:00,2180-03-23 18:09:00,None,NaN,mg/dL,10.0,10.0,None,ROUTINE,NEG. 80 (THESE UNITS) = 0.08 (% BY WEIGHT).
28,29,10000032,None,83925500,50924,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,90,90.0,ng/mL,13.0,150.0,None,ROUTINE,None
29,30,10000032,None,83925500,50927,P69FQC,2180-03-23 11:51:00,2180-03-23 16:40:00,69,69.0,IU/L,5.0,36.0,abnormal,ROUTINE,None